name: build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  universal:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12', '14']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: restore modules
      uses: actions/cache@v2
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node_version }}
          ${{ runner.os }}
    - name: Using Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Building
      run: |
        npm install
        npm run lint
        npm run build
